version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123xyz
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"

